version: '3'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-app
    volumes:
      - ./src/app:/app
    command: sh -c "npm run dev"
    tty: true
    ports:
      - 3000:3000
      - 6006:6006
  json-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: json-backend
    volumes:
      - ./json-backend:/app
    command: sh -c "npm ci && npm start"
    tty: true
    ports:
      - 8000:8000